### ISSUE TITLE
good practices #2 stream time

### ISSUE THREAD

**Issue by DamiXioR** [coders-school/fan_controller#1]
Dobre praktyki #2

Start 00:03:59
Co było ostatnio 00:05:33
From STUPID to SOLID code! 00:09:11
STUPID 00:14:08
Singleton 00:16:00
-> Wykrywanie zależności --gtest_shuffle 00:19:43
Tight Coupling 00:25:51
Untestability 00:28:35
Premature Optimization 00:30:29
-> Valgrind Callgrind 00:31:40
Indescriptive Naming 00:38:50
Duplication 00:40:57
SOLID 00:42:26
Single Responsibility Principle (SRP) 00:43:15
-> #protips 00:50:32
Open/Closed Principle (OCP) 00:53:05
-> #protips 00:59:38
Liskov Substitution Principle (LSP) 01:01:32
Interface Segregation Principle (ISP) 01:06:38
Dependency Inversion Principle (DIP) 01:12:47
Conclusion 01:19:20
SOLID w praktyce 01:24:24
Przerwa 01:35:40
Po przerwie 01:56:18
-> diagram uml 02:17:03
-> po diagramie 02:25:54
Pytania do SOLID w praktyce 02:46:16
SOLID w praktyce cd. 02:50:44
Praca domowa 03:00:50
Podsumowanie dzisiaj 03:06:40

**Comment by ziobron** [comment]
{ "requirement_ids": [4069] }
Thanks!
5 XP za utworzenie spisu treści do lekcji na YouTube (4069)
